# Jekyll Configuration for AutoDevHub GitHub Pages
# Based on ADR-006 Documentation Hosting Strategy

# Site settings
title: "AutoDevHub Documentation"
description: "AI-Powered DevOps Tracker - Capstone Project Documentation"
url: "https://ai-cohort-july-2025.github.io" # Update with actual GitHub Pages URL
baseurl: "" # Leave empty for user/org pages

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugin configuration
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# Collections
collections:
  adr:
    output: true
    permalink: /:collection/:name/
  architecture:
    output: true
    permalink: /:collection/:name/
  development:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "AI Cohort July 2025"
  - scope:
      path: ""
      type: "adr"
    values:
      layout: "page"
      nav_order: 3
  - scope:
      path: ""
      type: "architecture"
    values:
      layout: "page"
      nav_order: 2
  - scope:
      path: ""
      type: "development"
    values:
      layout: "page"
      nav_order: 4

# Navigation structure
navigation:
  - title: "Home"
    url: "/"
  - title: "Architecture"
    url: "/architecture/"
  - title: "ADRs"
    url: "/adr/"
  - title: "Development"
    url: "/development/"
  - title: "Presentation"
    url: "/presentation/"

# Mermaid diagram support
mermaid:
  src: 'https://unpkg.com/mermaid@10.6.0/dist/mermaid.min.js'

# SEO and social
author:
  name: "AI Cohort July 2025"
  email: "noreply@autodevhub.com"

social:
  - name: "GitHub"
    url: "https://github.com/ai-cohort-july-2025/AI-Cohort-July-2025"

# GitHub Pages specific settings
github_username: ai-cohort-july-2025
repository: AI-Cohort-July-2025

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - backend/
  - frontend/node_modules/
  - "*.pyc"
  - __pycache__/
  - .pytest_cache/
  - .coverage
  - docker-compose.yml
  - Dockerfile
  - "*.log"

# Include files
include:
  - _pages
  - assets

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Timezone
timezone: America/New_York

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Search settings
search_enabled: true

# Comments (GitHub Issues based)
comments:
  provider: "github"
  github:
    repository: "ai-cohort-july-2025/AI-Cohort-July-2025"

# Analytics (optional)
google_analytics: # Add GA tracking ID if needed

# Performance optimizations
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: ['development']