# AutoDevHub Documentation Site Configuration
title: "AutoDevHub Documentation"
description: "AI-Powered DevOps Tracker - Comprehensive Project Documentation"
baseurl: "/AI-Cohort-July-2025"
url: "https://ai-cohort-july-2025.github.io"

# GitHub Pages settings
remote_theme: minima
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mermaid

# Navigation structure
navigation:
  - title: "Home"
    url: "/"
  - title: "Architecture"
    url: "/docs/architecture/"
    children:
      - title: "System Overview"
        url: "/docs/architecture/system-overview/"
      - title: "API Specification"
        url: "/docs/architecture/api-specification/"
      - title: "Database Schema"
        url: "/docs/architecture/database-schema/"
  - title: "ADRs"
    url: "/docs/adr/"
  - title: "Development"
    url: "/docs/development/"
    children:
      - title: "Setup Guide"
        url: "/docs/development/setup-guide/"
      - title: "Deployment"
        url: "/docs/development/deployment/"
      - title: "Contributing"
        url: "/docs/development/contributing/"
  - title: "Presentation"
    url: "/docs/presentation/"

# Mermaid configuration
mermaid:
  src: 'https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js'

# SEO settings
author: "AI Cohort July 2025"
twitter:
  username: autodevhub
social:
  name: AutoDevHub
  links:
    - https://github.com/ai-cohort-july-2025/AI-Cohort-July-2025

# Build settings
theme: minima
exclude:
  - node_modules/
  - backend/
  - frontend/node_modules/
  - "*.log"
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - coordination/
  - memory/
  - old.CLAUDE.md

# Include documentation files
include:
  - docs/
  - README.md

# Collections
collections:
  adr:
    output: true
    permalink: /docs/adr/:name/
  architecture:
    output: true
    permalink: /docs/architecture/:name/

# Default settings
defaults:
  - scope:
      path: "docs"
    values:
      layout: "page"
  - scope:
      path: "docs/adr"
    values:
      layout: "page"
      parent: "Architecture Decision Records"
  - scope:
      path: "docs/architecture"
    values:
      layout: "page"
      parent: "Architecture"