# AutoDevHub Documentation Site Configuration
title: "AutoDevHub Documentation"
description: "AI-Powered DevOps Tracker - Comprehensive Project Documentation"
baseurl: "/AI-Cohort-July-2025"
url: "https://tbowman01.github.io"

# GitHub Pages settings
remote_theme: hydecorp/hydejack@v9
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mermaid
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-titles-from-headings

# Hydejack Navigation
menu:
  - title: Home
    url: /
  - title: Architecture
    url: /docs/architecture/
    submenu:
      - title: System Overview
        url: /docs/architecture/system-overview.html
      - title: API Specification  
        url: /docs/architecture/api-specification.html
      - title: Database Schema
        url: /docs/architecture/database-schema.html
  - title: ADRs
    url: /docs/adr/
  - title: Development
    url: /docs/development/
    submenu:
      - title: Setup Guide
        url: /docs/development/setup-guide.html
      - title: Deployment
        url: /docs/development/deployment.html
      - title: Contributing
        url: /docs/development/contributing.html
  - title: Presentation
    url: /docs/presentation/
    submenu:
      - title: Project Slides
        url: /docs/presentation/slides.html
      - title: Demo Script
        url: /docs/presentation/demo-script.html
  - title: Contact & Support
    url: /docs/contacts/

# Hydejack theme settings
hydejack:
  post_addons:    [about, newsletter, related, random]
  project_addons: [about, newsletter, other]
  no_mark_external: false
  no_push_state: false
  no_drawer: false
  no_navbar: false
  no_search: false
  no_inline_css: false
  no_page_style: false
  no_break_layout: true
  no_toc: false
  no_third_column: false
  no_large_headings: false
  no_structured_data: false
  no_theme_color: false
  use_lsi: true
  cookies_banner: false
  advertise: false
  hide_dates: false
  hide_last_modified: false

# Theme colors and appearance
accent_image:          /assets/img/sidebar-bg.jpg
accent_color:          rgb(79,177,186)
theme_color:           rgb(25,55,71)

# Mermaid configuration
mermaid:
  src: 'https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js'

# SEO settings
author: "AI Cohort July 2025"
twitter:
  username: autodevhub
social:
  name: AutoDevHub
  links:
    - https://github.com/ai-cohort-july-2025/AI-Cohort-July-2025

# Build settings
theme: minima
exclude:
  - node_modules/
  - backend/
  - frontend/
  - "*.log"
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - coordination/
  - memory/
  - old.CLAUDE.md
  - "README-*.md"
  - "*.lock"
  - ".bundle/"
  - "vendor/"
  - ".git/"
  - ".github/"
  - "test/"
  - "tests/"
  - "spec/"
  - "*.gemspec"

# Include documentation files
include:
  - docs/
  - README.md

# Collections
collections:
  adr:
    output: true
    permalink: /docs/adr/:name/
  architecture:
    output: true
    permalink: /docs/architecture/:name/

# Default settings
defaults:
  - scope:
      path: "docs"
    values:
      layout: "page"
  - scope:
      path: "docs/adr"
    values:
      layout: "page"
      parent: "Architecture Decision Records"
  - scope:
      path: "docs/architecture"
    values:
      layout: "page"
      parent: "Architecture"